name: Build and Deploy
'on':
    push:
      branches:
          - main

jobs:
    publish-package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - run: npm install
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
            - name: SMS Notification on Success
              if: ${{ success() }}
              uses: twilio-labs/actions-sms@v1
              with:
                fromPhoneNumber: ${{ secrets.TWILIO_FROM_NUMBER }}
                toPhoneNumber: ${{ secrets.MOBILE_NUMBER }}
                message: 'Smart Logger package published Successfully'
              env:
                TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
                TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
                TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
            - name: SMS Notification on Failure
              if: ${{ failure() }}
              uses: twilio-labs/actions-sms@v1
              with:
                fromPhoneNumber: ${{ secrets.TWILIO_FROM_NUMBER }}
                toPhoneNumber: ${{ secrets.MOBILE_NUMBER }}
                message: 'Smart Logger package publish Failure'
              env:
                TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
                TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
                TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}